### ISSUE TITLE
Fix HTTP URLs in views on Google Cloud Run

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/e-voting#7]
Some views still render http-urls, while we're on an https URL.

This breaks downloads and login pages.

How to reproduce:

1. Visit https://gumbo.nu/vote
1. Go to the login page
1. Check the source code
1. Notice an `action="http://<url>"` on the `<form>`-tag

**Comment by markwalet** [comment]
No.

**Comment by roelofr** [comment]
It seems HSTS picks up most issues. The browsers switch to HTTPS for us, since the domain is preloaded.

So the data is safe, but the prompts are annoying.

Edit: and the download API doesn't work 😢
